services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  db_setup:
    image: python:3.12-slim
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: db_for_openMeteo
    depends_on:
      - db
    command: python db_setup.py

  etl:
    image: python:3.12-slim
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: db_for_openMeteo
    depends_on:
      - db_setup

volumes:
  pg_data: